# Placeholder for hyprpaper
# This will be updated by the bing wallpaper script
preload = /home/jamesr/Pictures/bing_wallpaper/current.jpg
wallpaper = ,/home/jamesr/Pictures/bing_wallpaper/current.jpg
splash = false
