context.modules = [
    {   name = libpipewire-module-echo-cancel
        args = {
            node.name = "echo-cancel-source"
            node.description = "Echo Cancellation Source"
            source.props = {
                audio.rate = 48000
            }
            # The default library is webrtc
        }
    }
]
